In [1]:
import numpy as np

class NeuralNetwork:
    def __init__(self):
        np.random.seed(2)
        self.input_size = 3  # 3 input nodes (including the bias)
        self.hidden_size = 4  # number of nodes in the hidden layer
        self.output_size = 1  # 1 output node

        # Initialize weights
        self.weights_input_hidden = 2 * np.random.random((self.input_size, self.hidden_size)) - 1
        self.weights_hidden_output = 2 * np.random.random((self.hidden_size, self.output_size)) - 1

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def feedforward(self, inputs):
        # Calculate the activations in the hidden layer
        self.hidden_sum = np.dot(inputs, self.weights_input_hidden)
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        # Calculate the output using the hidden layer activations
        output_sum = np.dot(self.activated_hidden, self.weights_hidden_output)
        return self.sigmoid(output_sum)

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Forward propagation
            hidden_layer_output = self.sigmoid(np.dot(training_set_inputs, self.weights_input_hidden))
            output = self.sigmoid(np.dot(hidden_layer_output, self.weights_hidden_output))

            # Backpropagation
            output_error = training_set_outputs - output
            output_delta = output_error * self.sigmoid_derivative(output)

            hidden_error = output_delta.dot(self.weights_hidden_output.T)
            hidden_delta = hidden_error * self.sigmoid_derivative(hidden_layer_output)

            # Update weights
            self.weights_hidden_output += hidden_layer_output.T.dot(output_delta)
            self.weights_input_hidden += training_set_inputs.T.dot(hidden_delta)

# Example usage:

neural_network = NeuralNetwork()

    # Training data (example: XOR gate)
training_inputs = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
training_outputs = np.array([[0, 1, 1, 0]]).T

    # Train the neural network
neural_network.train(training_inputs, training_outputs, number_of_training_iterations=10000)
print('New Weights after Training\n')
print(neural_network.weights_hidden_output)
print()

    # Test the neural network with a new situation
print("Considering new situation [1, 0, 0] -> ?:")
print(neural_network.feedforward(np.array([1, 0, 0])))

New Weights after Training

[[ -0.43323277]
 [-11.04878773]
 [ -5.16474862]
 [ 10.17497628]]

Considering new situation [1, 0, 0] -> ?:
[0.01003412]


In [2]:
from numpy import exp
from numpy import array
from numpy import random,dot

In [3]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define the multilayer perceptron class
class MLP:
    def __init__(self, input_size, hidden_size, output_size):
        # Initialize the weights and biases for the input to hidden layer
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        self.bias_hidden = np.zeros((1, hidden_size))

        # Initialize the weights and biases for the hidden to output layer
        self.weights_hidden_output = np.random.rand(hidden_size, output_size)
        self.bias_output = np.zeros((1, output_size))

    def forward(self, inputs):
        # Forward pass through the input to hidden layer
        self.hidden_input = np.dot(inputs, self.weights_input_hidden) + self.bias_hidden
        self.hidden_output = sigmoid(self.hidden_input)

        # Forward pass through the hidden to output layer
        self.output_input = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output
        self.output = sigmoid(self.output_input)

    def train(self, inputs, targets, learning_rate):
        # Compute the loss and error
        error = targets - self.output

        # Backpropagation for the hidden to output layer
        delta_output = error * sigmoid_derivative(self.output)
        d_weights_hidden_output = np.dot(self.hidden_output.T, delta_output)
        d_bias_output = np.sum(delta_output, axis=0, keepdims=True)

        # Backpropagation for the input to hidden layer
        delta_hidden = np.dot(delta_output, self.weights_hidden_output.T) * sigmoid_derivative(self.hidden_output)
        d_weights_input_hidden = np.dot(inputs.T, delta_hidden)
        d_bias_hidden = np.sum(delta_hidden, axis=0, keepdims=True)

        # Update the weights and biases
        self.weights_hidden_output += learning_rate * d_weights_hidden_output
        self.bias_output += learning_rate * d_bias_output
        self.weights_input_hidden += learning_rate * d_weights_input_hidden
        self.bias_hidden += learning_rate * d_bias_hidden

# Example usage
input_size = 2
hidden_size = 3
output_size = 1

mlp = MLP(input_size, hidden_size, output_size)

# Training data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Training loop
epochs = 10000
learning_rate = 0.1

for epoch in range(epochs):
    mlp.forward(X)
    mlp.train(X, y, learning_rate)
    if epoch % 1000 == 0:
        loss = np.mean(np.square(y - mlp.output))
        print(f"Epoch {epoch}: Loss = {loss}")

# Test the trained network
mlp.forward(X)
print("Final Output:")
print(mlp.output)

Epoch 0: Loss = 0.259627939746805
Epoch 1000: Loss = 0.24969511174980363
Epoch 2000: Loss = 0.24816158747371303
Epoch 3000: Loss = 0.23235307008533646
Epoch 4000: Loss = 0.17318162603011783
Epoch 5000: Loss = 0.0886034102547329
Epoch 6000: Loss = 0.027788957698441592
Epoch 7000: Loss = 0.01172737134316031
Epoch 8000: Loss = 0.006849070033813804
Epoch 9000: Loss = 0.004699268497330416
Final Output:
[[0.06525135]
 [0.94392417]
 [0.94371639]
 [0.05947493]]


In [4]:
from numpy import exp
from numpy import array
from numpy import random,dot

In [5]:
class NeuralNetwork():
    def __init__(self):

 #seed the random number generator ,so it generates the same numbers
 #every time the program runs
        random.seed(2)
 #we model a single neuron with 3 input and 1 output connection
 #we assign a random weights to a 3*1 matrix with values in the rang
        self.synaptic_weights=2*random.random((3,1))-1

 #Crete a sigmoid activation function
    def __sigmoid(self,x):
        return 1/1+exp(-x)

    def __sigmoid_derivative(self,x):
        return x*(1-x)

    def think(self,inputs):
        return self.__sigmoid(dot(inputs,self.synaptic_weights))

    def train(self,training_set_inputs,training_set_outputs,number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            output=self.think(training_set_inputs)
            error=training_set_outputs-output
            adjusment=dot(training_set_inputs.T,error*self.__sigmoid_derivative(output))

            #adjust three weights
            self.synaptic_weights+=adjusment

In [6]:
if __name__=='__main__':

 # Initialize a single neuron neural networks
    neural_network=NeuralNetwork()
    print('Random starting weights:\n')
    print(neural_network.synaptic_weights)

    training_set_inputs=array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
    training_set_outputs=array([[0,1,1,0]]).T

Random starting weights:

[[-0.1280102 ]
 [-0.94814754]
 [ 0.09932496]]


In [7]:
#Train the networks
print('********************* Neural Network Training Phase*****************\n')
neural_network.train(training_set_inputs,training_set_outputs,10000)
print('New weights after training\n')
print(neural_network.synaptic_weights)
print()
#Test the networks
print('Considering the new situation [1,0,0]--> ?:')
print()
print(neural_network.think(array([1,0,0])))


********************* Neural Network Training Phase*****************

New weights after training

[[27.81236918]
 [50.86430059]
 [57.34813037]]

Considering the new situation [1,0,0]--> ?:

[1.]
